FROM ubuntu:18.04

LABEL       author="YuyuLuna" maintainer="admin@mail.yuyucloud.com"

RUN apt update && apt -y install openjdk-11-jre curl ca-certificates openssl git tar bash sqlite fontconfig \
    && adduser -D -h /home/container container

RUN echo "Asia/Taipei" > /etc/timezone;dpkg-reconfigure -f noninteractive tzdata

USER container
ENV  USER=container HOME=/home/container
ENV TZ Asia/Taipei

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
